language: generic

script:
  - make
  - make test

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc5
      env:
        - CC=gcc-5
        - CXX=g++-5

        # Travis is so parallel it runs out of memory. Limit that.
        - NINJA_JOBS=2
      addons:
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libxml2-dev
            - ninja-build
            - cmake
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      before_install:
        - brew update
      install:
        - brew reinstall cmake
        - brew reinstall ninja
